language: generic
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
before_install:
- gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- \curl -sSL https://get.rvm.io | bash -s stable
- rvm reload
- rvm use ruby-2.3.1 --default 
- sudo -E apt-get install rubygems
- gem install coveralls-lcov

before_script:
- sudo rm /usr/bin/gcc
- sudo rm /usr/bin/g++
- sudo rm /usr/bin/gcov
- sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-6 /usr/bin/g++
- sudo ln -s /usr/bin/gcov-6 /usr/bin/gcov

script:
- make server_ut_gcov_run -j40

after_success:
- git clone https://github.com/linux-test-project/lcov.git
- chmod +x lcov/bin/lcov
- ./lcov/bin/lcov -c -b . -d ../build/gcov/ > ut_coverage.info
- ./lcov/bin/lcov -r ut_coverage.info '/usr/include*' '*/gtest/g*' > clean_ut_coverage.info
- coveralls-lcov --repo-token ${COVTOK} clean_ut_coverage.info

notifications:
  slack: propertytree-dev:zSmmGWnuAgtGaTI7dDNtFkml
